import { ethers } from "hardhat";
import { Signer } from "ethers";
import * as fs from "fs";
import * as path from "path";

// Define the structure for contract addresses
// Note: Changed property names to lowercase consistent with the frontend config naming.
interface DeployedContractAddresses {
    shopCAPToken: string;
    partnerRegistry: string;
    cashbackManager: string;
    shopCAPPlatform: string;
}

// Define the chain constants
const SEPOLIA_CHAIN_ID = 11155111; // Sepolia Testnet decimal ID
const SEPOLIA_CHAIN_NAME = "Sepolia"; // Sepolia Testnet name

async function main() {
    // Get the deployer account
    const [deployer]: Signer[] = await ethers.getSigners();
    const deployerAddress = await deployer.getAddress();
    console.log("Deploying contracts with account:", deployerAddress);

    // --- 1. Deploy ShopCAPToken ---
    // Get the contract factory for "ShopCAPToken".
    const ShopCAPTokenFactory = await ethers.getContractFactory("ShopCAPToken");
    const shopCAPToken = await ShopCAPTokenFactory.deploy();
    await shopCAPToken.waitForDeployment();
    const deployedShopCAPTokenAddress = await shopCAPToken.getAddress();
    console.log(`ShopCAPToken deployed to: ${deployedShopCAPTokenAddress}`);

    // --- 2. Deploy PartnerRegistry ---
    // Similar steps for PartnerRegistry.
    const PartnerRegistryFactory = await ethers.getContractFactory(
        "PartnerRegistry"
    );
    const partnerRegistry = await PartnerRegistryFactory.deploy();
    await partnerRegistry.waitForDeployment();
    const deployedPartnerRegistryAddress = await partnerRegistry.getAddress();
    console.log(
        `PartnerRegistry deployed to: ${deployedPartnerRegistryAddress}`
    );

    // --- 3. Deploy CashbackManager ---
    const CashbackManagerFactory = await ethers.getContractFactory(
        "CashbackManager"
    );
    const cashbackManager = await CashbackManagerFactory.deploy(
        deployedShopCAPTokenAddress,
        deployedPartnerRegistryAddress,
        deployerAddress
    );
    await cashbackManager.waitForDeployment();
    const deployedCashbackManagerAddress = await cashbackManager.getAddress();
    console.log(
        `CashbackManager deployed to: ${deployedCashbackManagerAddress}`
    );

    // --- 4. Deploy ShopCAPPlatform ---
    const ShopCAPPlatformFactory = await ethers.getContractFactory(
        "ShopCAPPlatform"
    );
    const shopCAPPlatform = await ShopCAPPlatformFactory.deploy(
        deployedPartnerRegistryAddress,
        deployedCashbackManagerAddress
    );
    await shopCAPPlatform.waitForDeployment();
    const deployedShopCAPPlatformAddress = await shopCAPPlatform.getAddress();
    console.log(
        `ShopCAPPlatform deployed to: ${deployedShopCAPPlatformAddress}`
    );

    // --- Transfer Ownership of CashbackManager to ShopCAPPlatform ---
    console.log(
        "\nTransferring ownership of CashbackManager to ShopCAPPlatform..."
    );
    const transferOwnershipTx = await cashbackManager
        .connect(deployer)
        .transferOwnership(deployedShopCAPPlatformAddress);
    await transferOwnershipTx.wait(); // Wait for the transaction to be mined
    console.log(
        `Ownership of CashbackManager successfully transferred to ShopCAPPlatform.`
    );

    // --- Frontend Configuration Generation ---
    console.log("\nStarting frontend configuration file generation...");

    const frontendDir = path.join(__dirname, "../frontend"); // Path to your frontend directory
    const frontendUtilsDir = path.join(frontendDir, "src", "utils"); // Where contract-config.js will be
    const frontendAbiDir = path.join(frontendDir, "src", "contracts", "abi"); // Where full ABI JSONs will be copied

    // Ensure directories exist
    fs.mkdirSync(frontendUtilsDir, { recursive: true });
    fs.mkdirSync(frontendAbiDir, { recursive: true });

    // 1. Generate contract-config.js
    const currentDeployedContractAddresses: DeployedContractAddresses = {
        shopCAPToken: deployedShopCAPTokenAddress,
        partnerRegistry: deployedPartnerRegistryAddress,
        cashbackManager: deployedCashbackManagerAddress,
        shopCAPPlatform: deployedShopCAPPlatformAddress,
    };

    // Construct the content for contract-config.js
    const contractConfigFileContent = `
// This file is automatically generated by the Hardhat deploy script.
// DO NOT EDIT THIS FILE MANUALLY!

// Import full ABI JSONs directly. These are copied from artifacts.
import ShopCAPTokenABI from "../contracts/abi/ShopCAPToken.json";
import PartnerRegistryABI from "../contracts/abi/PartnerRegistry.json";
import CashbackManagerABI from "../contracts/abi/CashbackManager.json";
import ShopCAPPlatformABI from "../contracts/abi/ShopCAPPlatform.json";

// Contract addresses for different networks
export const contractAddresses = {
    // Sepolia Chain ID (decimal: ${SEPOLIA_CHAIN_ID}, hex: 0x${SEPOLIA_CHAIN_ID.toString(
        16
    )})
    ${SEPOLIA_CHAIN_ID}: {
        shopCAPToken: "${currentDeployedContractAddresses.shopCAPToken}",
        partnerRegistry: "${currentDeployedContractAddresses.partnerRegistry}",
        cashbackManager: "${currentDeployedContractAddresses.cashbackManager}",
        shopCAPPlatform: "${currentDeployedContractAddresses.shopCAPPlatform}",
    },
    // Add other network addresses here if needed
};

// Contract ABIs (network independent). We extract the 'abi' property from the full artifact.
export const contractABIs = {
    ShopCAPToken: ShopCAPTokenABI.abi,
    PartnerRegistry: PartnerRegistryABI.abi,
    CashbackManager: CashbackManagerABI.abi,
    ShopCAPPlatform: ShopCAPPlatformABI.abi,
};

// Expected network for connection
export const EXPECTED_CHAIN_ID = "${SEPOLIA_CHAIN_ID}";
export const EXPECTED_CHAIN_NAME = "${SEPOLIA_CHAIN_NAME}";
`;

    const contractConfigFilePath = path.join(
        frontendUtilsDir,
        "contract-config.js"
    );
    fs.writeFileSync(contractConfigFilePath, contractConfigFileContent);
    console.log(
        `Frontend contract configuration saved to: ${contractConfigFilePath}`
    );

    // 2. Copy full ABI files (including bytecode, etc.)
    const contractNames = [
        "ShopCAPToken",
        "PartnerRegistry",
        "CashbackManager",
        "ShopCAPPlatform",
    ];

    for (const name of contractNames) {
        const abiSourcePath = path.join(
            __dirname,
            `../artifacts/contracts/${name}.sol/${name}.json`
        );
        const abiDestPath = path.join(frontendAbiDir, `${name}.json`);

        if (fs.existsSync(abiSourcePath)) {
            // Read the entire artifact JSON
            const fullArtifact = fs.readFileSync(abiSourcePath, "utf8");
            // Write the full artifact to the frontend abi folder
            fs.writeFileSync(abiDestPath, fullArtifact); // Write full JSON without parsing and re-stringifying
            console.log(
                `Full ABI artifact for ${name} copied to: ${abiDestPath}`
            );
        } else {
            console.warn(
                `Warning: Full ABI artifact file not found for ${name} at path ${abiSourcePath}.`
            );
        }
    }
    console.log("Frontend configuration generation completed successfully.");

    // --- Verification Commands Output ---
    console.log("\n---------- VERIFICATION COMMANDS ----------");
    console.log(
        "IMPORTANT: Save these commands! They are needed for Etherscan verification (e.g., for Sepolia)."
    );
    console.log(
        "Ensure you have the @nomicfoundation/hardhat-verify plugin installed and ETHERSCAN_API_KEY configured in your .env file."
    );
    console.log(
        "Execute these commands MANUALLY, ONE BY ONE, after deployment and when transactions are fully confirmed."
    );

    console.log(`\n// Verify ShopCAPToken (no constructor arguments)`);
    console.log(
        `npx hardhat verify --network sepolia ${deployedShopCAPTokenAddress}`
    );

    console.log(`\n// Verify PartnerRegistry (no constructor arguments)`);
    console.log(
        `npx hardhat verify --network sepolia ${deployedPartnerRegistryAddress}`
    );

    console.log(`\n// Verify CashbackManager (with constructor arguments)`);
    console.log(
        `npx hardhat verify --network sepolia ${deployedCashbackManagerAddress} "${deployedShopCAPTokenAddress}" "${deployedPartnerRegistryAddress}" "${deployerAddress}"`
    );

    console.log(`\n// Verify ShopCAPPlatform (with constructor arguments)`);
    console.log(
        `npx hardhat verify --network sepolia ${deployedShopCAPPlatformAddress} "${deployedPartnerRegistryAddress}" "${deployedCashbackManagerAddress}"`
    );
    console.log("-------------------------------------------\n");
}

// Call the main deployment function and handle errors.
main()
    .then(() => process.exit(0)) // Exit the process with success code
    .catch((error) => {
        console.error(error); // Log the error to console
        process.exit(1); // Exit the process with error code
    });
